ignore:
  - "**/controlador/*"
  - "**/vista/*"
  - "**/archivos/*"
  - "**/Main.java"
  - "**/App.java"
  - "**/SystemInfo.java"
  - "**/SetUpJuego.java"
  - "src/main/java/edu/fiuba/algo3/vista"
  - "src/main/java/edu/fiuba/algo3/vista/**/*"
  - "src/main/java/edu/fiuba/algo3/controlador"
  - "src/main/java/edu/fiuba/algo3/controlador/**/*"